#!/bin/sh

echo
echo "Virtlab Debian Virtual Machine image customization script starting ..."
echo

# to export the public key gpg --output public.key --armor --export)
echo "apt-key add  public vlab key"
PUBKEY_URL="http://virtlab.unibo.it/public.key"
wget -O - $PUBKEY_URL | apt-key add -

echo ""
echo "Copy sources.list and startup files ..."
echo ""

/bin/cp -v sources.list /etc/apt
/bin/cp -v vmFirstStartup /usr/local/bin
chmod 755 /usr/local/bin/vmFirstStartup
/bin/cp -v vmFirstStartup.service /etc/systemd/system

echo ""
echo "Update and install the needed packages ..."
echo ""


apt-get update 
apt-get -y upgrade
apt-get -y install sudo python-glade2 build-essential network-manager-openvpn-gnome network-manager-openvpn openvpn vim gedit build-essential

#echo ""
#echo "Customize Network Manager VPN connections"
#echo ""

#/bin/cp -v unibo /etc/NetworkManager/system-connections
#service network-manager restart

echo ""
echo "Set the system to start user customization script as first service of the next first boot"
echo ""

# at the end of vmFirstStartup "systemctl set-default graphical.target" "systemctl disable vmFirstStartup.service"
systemctl set-default multi-user.target
systemctl enable vmFirstStartup.service

echo ""
echo "Type reboot to restart system now, or poweroff to shutdown the vm without restart!"
echo ""


