development:
  encoding: utf8
  adapter:  mysql2
  database: cpkg
  username: cpkg
  password: ihdsdlkdlkewldkldklqklaaad
  socket: /var/run/mysqld/mysqld.sock

test: &TEST
  encoding: utf8
  adapter:  mysql2
  database: gemma_test
  username: gemma
  password: miapassword
  host:     localhost



