#!/bin/bash

set -x

if [[ -z "${CPKG_BASEDIR}" ]]; then
  echo "Missing CPKG_BASEDIR variable. Check your $HOME/.bashrc file"
  exit 1
fi

VLAB_CORE_SRC_DIR="${CPKG_BASEDIR}/vlab-core"
BUILD_DIR="/tmp/build_dir"

mkdir -v $BUILD_DIR
cd $BUILD_DIR

# 2018031601
version=`grep -oP "[0-9]{10}" ${VLAB_CORE_SRC_DIR}/debian/changelog`
echo "*** version: ${version}"

# vlab-core_20180316.orig.tar.gz
current_date=`date "+%Y%m%d"`
orig_archive_filename="vlab-core_${current_date}.orig.tar.gz"
echo "*** orig_archive_filename: ${orig_archive_filename}"

# vlab-core-2018032903
folder_name="vlab-core-"${version}
echo "*** folder_name: ${folder_name}"

mkdir -pv $folder_name 

echo "*** copy debian src files ${VLAB_CORE_SRC_DIR}/* in ${folder_name}"
echo "*** and create tar ${orig_archive_filename} in ${BUILD_DIR}"

cp -rv ${VLAB_CORE_SRC_DIR}/* ${folder_name}

tar -czf $orig_archive_filename $folder_name

echo   "*** creating version ${version} of vlab-core"
logger "creating version ${version} of vlab-core in ${BUILD_DIR}/${folder_name}"

cd $folder_name/debian

# -uc comes from dpkg-buildpackage (-uc, --unsigned-changes Do not sign the .buildinfo and .changes files)
# -us comes from dpkg-buildpackage (-us, --unsigned-source)
/usr/bin/debuild -us -uc

cd $BUILD_DIR
cp -v vlab-core_${version}* ${CPKG_BASEDIR}/reprepro/incoming

/usr/bin/reprepro -v --confdir ${CPKG_BASEDIR}/reprepro/conf --basedir /var/www/repo processincoming stretch






